### ISSUE TITLE
should add autocomplete for kubectl

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/kubernetes-stack-cookbook#11]
autocomplete should work out of the box by default.

see: https://kubernetes.io/docs/user-guide/kubectl-cheatsheet/

**Comment by hoatle** [comment]
@hieptranquoc this did not work to me with the latest merge changes.

**Comment by hieptranquoc** [comment]
@hoatle fixed! Review for me, plz

**Comment by hoatle** [comment]
reopened to verify before closing.

**Comment by hoatle** [comment]
verified, closed.
